* Description  
Qutefox is a Firefox configuration with aims to add some [[https://qutebrowser.org/][Qutebrowser]] like fetchers as well as utilize a 16:9 display more efficiently.

* Install 
Right now I only have the install instructions for GNU/Linux but the instructions shod be similar on window but with different file locations and different file locations and some things done in a windowser way.

**** GNU/Linux 
Open Firefox and enter into the omnibar/urlbar "about:profile" click the create a new profile button the go thru the prompt. This step is optional but other wise you will be over writing your previous profile with Qutefox.

Copy the "chrome" folder to the Qutefox profiles folder in "~/.mozilla/firefox/[Profile]".
#+BEGIN_SRC shell
cp -r Qutefox/chrome ~/.mozilla/firefox/[Profie]
#+END_SRC

Either restart Firefox or launch the profile from about:profile. Enter in to the omnibar/urlbar "about:config", click accept the risk and continue. In the search feel enter "toolkit.legacyUserProfileCustomizations.stylesheets" then double click on the result to set the value to true. Then restart Firefox.

Then install the below plugins by clicking the link then the add to Firefox button.
+ [[https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search][Vimium-FF]]
+ [[https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/][Tab Center Redux]]

Click the Hamburger menu in the bottom right corner then click customize. In the bottom left set the density to compact.
